UPDATE spesies SET image_url = '/assets/spesies/adonis.jpg' WHERE nama_umum = 'ADONIS';
UPDATE spesies SET image_url = '/assets/spesies/american_snoot.jpg' WHERE nama_umum = 'AMERICAN SNOOT';
UPDATE spesies SET image_url = '/assets/spesies/an_88.jpg' WHERE nama_umum = 'AN 88';
UPDATE spesies SET image_url = '/assets/spesies/banded_peacock.jpg' WHERE nama_umum = 'BANDED PEACOCK';
UPDATE spesies SET image_url = '/assets/spesies/beckers_white.jpg' WHERE nama_umum = 'BECKERS WHITE';
UPDATE spesies SET image_url = '/assets/spesies/black_hairstreak.jpg' WHERE nama_umum = 'BLACK HAIRSTREAK';
UPDATE spesies SET image_url = '/assets/spesies/cabbage_white.jpg' WHERE nama_umum = 'CABBAGE WHITE';
UPDATE spesies SET image_url = '/assets/spesies/chestnut.jpg' WHERE nama_umum = 'CHESTNUT';
UPDATE spesies SET image_url = '/assets/spesies/clodius_parnassian.jpg' WHERE nama_umum = 'CLODIUS PARNASSIAN';
UPDATE spesies SET image_url = '/assets/spesies/clouded_sulphur.jpg' WHERE nama_umum = 'CLOUDED SULPHUR';
UPDATE spesies SET image_url = '/assets/spesies/copper_tail.jpg' WHERE nama_umum = 'COPPER TAIL';
UPDATE spesies SET image_url = '/assets/spesies/crecent.jpg' WHERE nama_umum = 'CRECENT';
UPDATE spesies SET image_url = '/assets/spesies/crimson_patch.jpg' WHERE nama_umum = 'CRIMSON PATCH';
UPDATE spesies SET image_url = '/assets/spesies/eastern_coma.jpg' WHERE nama_umum = 'EASTERN COMA';
UPDATE spesies SET image_url = '/assets/spesies/gold_banded.jpg' WHERE nama_umum = 'GOLD BANDED';
UPDATE spesies SET image_url = '/assets/spesies/great_eggfly.jpg' WHERE nama_umum = 'GREAT EGGFLY';
UPDATE spesies SET image_url = '/assets/spesies/grey_hairstreak.jpg' WHERE nama_umum = 'GREY HAIRSTREAK';
UPDATE spesies SET image_url = '/assets/spesies/indra_swallow.jpg' WHERE nama_umum = 'INDRA SWALLOW';
UPDATE spesies SET image_url = '/assets/spesies/julia.jpg' WHERE nama_umum = 'JULIA';
UPDATE spesies SET image_url = '/assets/spesies/large_marble.jpg' WHERE nama_umum = 'LARGE MARBLE';
UPDATE spesies SET image_url = '/assets/spesies/malachite.jpg' WHERE nama_umum = 'MALACHITE';
UPDATE spesies SET image_url = '/assets/spesies/mangrove_skipper.jpg' WHERE nama_umum = 'MANGROVE SKIPPER';
UPDATE spesies SET image_url = '/assets/spesies/metalmark.jpg' WHERE nama_umum = 'METALMARK';
UPDATE spesies SET image_url = '/assets/spesies/monarch.jpg' WHERE nama_umum = 'MONARCH';
UPDATE spesies SET image_url = '/assets/spesies/morning_cloak.jpg' WHERE nama_umum = 'MORNING CLOAK';
UPDATE spesies SET image_url = '/assets/spesies/orange_oakleaf.jpg' WHERE nama_umum = 'ORANGE OAKLEAF';
UPDATE spesies SET image_url = '/assets/spesies/orange_tip.jpg' WHERE nama_umum = 'ORANGE TIP';
UPDATE spesies SET image_url = '/assets/spesies/orchard_swallow.jpg' WHERE nama_umum = 'ORCHARD SWALLOW';
UPDATE spesies SET image_url = '/assets/spesies/painted_lady.jpg' WHERE nama_umum = 'PAINTED LADY';
UPDATE spesies SET image_url = '/assets/spesies/paper_kite.jpg' WHERE nama_umum = 'PAPER KITE';
UPDATE spesies SET image_url = '/assets/spesies/peacock.jpg' WHERE nama_umum = 'PEACOCK';
UPDATE spesies SET image_url = '/assets/spesies/pine_white.jpg' WHERE nama_umum = 'PINE WHITE';
UPDATE spesies SET image_url = '/assets/spesies/pipevine_swallow.jpg' WHERE nama_umum = 'PIPEVINE SWALLOW';
UPDATE spesies SET image_url = '/assets/spesies/purple_hairstreak.jpg' WHERE nama_umum = 'PURPLE HAIRSTREAK';
UPDATE spesies SET image_url = '/assets/spesies/question_mark.jpg' WHERE nama_umum = 'QUESTION MARK';
UPDATE spesies SET image_url = '/assets/spesies/red_admiral.jpg' WHERE nama_umum = 'RED ADMIRAL';
UPDATE spesies SET image_url = '/assets/spesies/red_spotted_purple.jpg' WHERE nama_umum = 'RED SPOTTED PURPLE';
UPDATE spesies SET image_url = '/assets/spesies/scarce_swallow.jpg' WHERE nama_umum = 'SCARCE SWALLOW';
UPDATE spesies SET image_url = '/assets/spesies/silver_spot_skipper.jpg' WHERE nama_umum = 'SILVER SPOT SKIPPER';
UPDATE spesies SET image_url = '/assets/spesies/sixspot_burnet.jpg' WHERE nama_umum = 'SIXSPOT BURNET';
UPDATE spesies SET image_url = '/assets/spesies/skipper.jpg' WHERE nama_umum = 'SKIPPER';
UPDATE spesies SET image_url = '/assets/spesies/sootywing.jpg' WHERE nama_umum = 'SOOTYWING';
UPDATE spesies SET image_url = '/assets/spesies/southern_dogface.jpg' WHERE nama_umum = 'SOUTHERN DOGFACE';
UPDATE spesies SET image_url = '/assets/spesies/straited_queen.jpg' WHERE nama_umum = 'STRAITED QUEEN';
UPDATE spesies SET image_url = '/assets/spesies/two_barred_flasher.jpg' WHERE nama_umum = 'TWO BARRED FLASHER';
UPDATE spesies SET image_url = '/assets/spesies/ulyses.jpg' WHERE nama_umum = 'ULYSES';
UPDATE spesies SET image_url = '/assets/spesies/viceroy.jpg' WHERE nama_umum = 'VICEROY';
UPDATE spesies SET image_url = '/assets/spesies/wood_satyr.jpg' WHERE nama_umum = 'WOOD SATYR';
UPDATE spesies SET image_url = '/assets/spesies/yellow_swallow_tail.jpg' WHERE nama_umum = 'YELLOW SWALLOW TAIL';
UPDATE spesies SET image_url = '/assets/spesies/zebra_long_wing.jpg' WHERE nama_umum = 'ZEBRA LONG WING';
